### ISSUE TITLE
Error POST https://guycol.tk/checkout/?wc-ajax=checkout 500 (Internal Server Error)

### ISSUE THREAD

**Issue by lukasfeliphe** [jarysardinha/woocommerce-stelo#1]
Hello Jary,

Your Module is a Awesome, but i cant´t pay order, in  moment of payment the post return error 500.

you can help me ?

Thanks!

**Comment by jarysardinha** [comment]
Claro,

Me passa uma print de como você está mandando o formulário de pagamento para eu replicar e poder ver o que pode ser por aqui.

**Comment by lukasfeliphe** [comment]
![image](https://user-images.githubusercontent.com/30473853/30294218-b3d5f08e-9712-11e7-8e2d-4942a545c817.png)

**Comment by lukasfeliphe** [comment]
estou usando woocommerce 3.0 e jquery 1.12

**Comment by jarysardinha** [comment]
Aperte em Network, me falei os Headers que estão sendo enviados clicando no último request do XHR do wc-chekout. Aqui segue normal.

**Comment by lukasfeliphe** [comment]
Ele está dando esse erro
![image](https://user-images.githubusercontent.com/30473853/30301353-9ea58328-9730-11e7-84a4-2f24338c7df3.png)

500 Internal Server Error

**Comment by lukasfeliphe** [comment]
Aparece esse erro ao tentar finalizar compra, já revirei e ainda não achei o erro

![image](https://user-images.githubusercontent.com/30473853/30301384-d3b609c0-9730-11e7-8a81-48efbec3b93d.png)

**Comment by lukasfeliphe** [comment]
Agora coloquei em modo debug, olha a resposta 

![image](https://user-images.githubusercontent.com/30473853/30302148-84855216-9735-11e7-9ff3-598c9a3bf90d.png)

**Comment by lukasfeliphe** [comment]
Então, corrigi algumas coisas e agora respondeu 200 mas agora dá algum erro que realmente não sei

![image](https://user-images.githubusercontent.com/30473853/30303137-3b9576a6-973c-11e7-89b6-9ed4f8410ed8.png)

Erro ao finalizar a compra. Por favor tente novamente
